project:
  type: website
  output-dir: docs

website:
  title: "Hannah Lyons"
  site-url: https://hannahl8.github.io/
  description: "This is Hannah Lyons Personal Blog"
  repo-url: https://github.com/hannahl8/hannahl8.github.io
  repo-actions: [source]
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: About
        href: index.qmd
      - text: Archive
        href: archive.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/hannah-lyons-l8/
      - icon: github
        href: https://github.com/hannahl8
format:
  html:
    theme: vapor
    css: styles.css

editor: visual